<?php

namespace App\Services\PresentationGenerator;

use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Style\Font;
use Illuminate\Support\Facades\Log;

class DocxGenerator
{
    protected $phpWord;
    protected $section;

    /**
     * Word hujjat yaratish
     */
    public function generate($contentData, $studentInfo, $outputPath)
    {
        try {
            // Yangi Word hujjat
            $this->phpWord = new PhpWord();

            // Hujjat xususiyatlari
            $this->setupDocumentProperties($contentData['title'], $studentInfo);

            // Section yaratish (A4 sahifa)
            $this->section = $this->phpWord->addSection([
                'marginTop' => 1440,    // 1 inch = 1440 twips
                'marginBottom' => 1440,
                'marginLeft' => 1440,
                'marginRight' => 1440,
            ]);

            // Talaba ma'lumotlari (agar birinchi sahifaga)
            if ($studentInfo['info_placement'] === 'first') {
                $this->addStudentInfo($studentInfo, $contentData['title']);
                $this->section->addPageBreak();
            }

            // Kontent
            foreach ($contentData['slides'] as $index => $slideData) {
                $this->addContentPage($slideData);

                // Oxirgi sahifadan boshqa hammaga page break
                if ($index < count($contentData['slides']) - 1 ||
                    $studentInfo['info_placement'] === 'last') {
                    $this->section->addPageBreak();
                }
            }

            // Talaba ma'lumotlari (agar oxirgi sahifaga)
            if ($studentInfo['info_placement'] === 'last') {
                $this->addStudentInfo($studentInfo, $contentData['title']);
            }

            // Faylni saqlash
            $this->saveDocument($outputPath);

            return [
                'success' => true,
                'file_path' => $outputPath,
                'file_size' => filesize($outputPath)
            ];

        } catch (\Exception $e) {
            Log::error('DOCX Generation Error: ' . $e->getMessage());
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Hujjat xususiyatlari
     */
    protected function setupDocumentProperties($title, $studentInfo)
    {
        $properties = $this->phpWord->getDocInfo();
        $properties->setCreator($studentInfo['first_name']);
        $properties->setTitle($title);
        $properties->setSubject($title);
        $properties->setDescription("Generated by Telegram Presentation Bot");
        $properties->setCategory("Education");
    }

    /**
     * Talaba ma'lumotlari sahifasi
     */
    protected function addStudentInfo($studentInfo, $title)
    {
        // Sarlavha (centered, katta)
        $this->section->addText(
            $title,
            ['size' => 28, 'bold' => true, 'color' => '2C3E50'],
            ['alignment' => 'center', 'spaceAfter' => 400]
        );

        $this->section->addTextBreak(2);

        // Universitet
        $this->section->addText(
            '🎓 ' . $studentInfo['university'],
            ['size' => 16, 'bold' => true],
            ['alignment' => 'center', 'spaceAfter' => 200]
        );

        // Yo'nalish
        $this->section->addText(
            '📚 ' . $studentInfo['direction'],
            ['size' => 14],
            ['alignment' => 'center', 'spaceAfter' => 200]
        );

        // Guruh
        $this->section->addText(
            '👥 Guruh: ' . $studentInfo['group_name'],
            ['size' => 14],
            ['alignment' => 'center', 'spaceAfter' => 200]
        );

        // Talaba ismi
        if (!empty($studentInfo['first_name'])) {
            $this->section->addText(
                '👤 ' . $studentInfo['first_name'],
                ['size' => 12],
                ['alignment' => 'center']
            );
        }
    }

    /**
     * Kontent sahifasi
     */
    protected function addContentPage($slideData)
    {
        // Sarlavha
        $this->section->addText(
            $slideData['title'],
            ['size' => 20, 'bold' => true, 'color' => '2C3E50'],
            ['spaceAfter' => 300]
        );

        // Kontent (bullet list)
        foreach ($slideData['content'] as $point) {
            $this->section->addListItem(
                $point,
                0,  // depth level
                ['size' => 12, 'color' => '34495E'],
                ['spaceAfter' => 120]
            );
        }
    }

    /**
     * Hujjatni saqlash
     */
    protected function saveDocument($outputPath)
    {
        // Papkani yaratish
        $directory = dirname($outputPath);
        if (!file_exists($directory)) {
            mkdir($directory, 0755, true);
        }

        // Word 2007 formatida saqlash
        $writer = IOFactory::createWriter($this->phpWord, 'Word2007');
        $writer->save($outputPath);
    }
}
