<?php

namespace App\Services\PresentationGenerator;

use PhpOffice\PhpPresentation\PhpPresentation;
use PhpOffice\PhpPresentation\IOFactory;
use PhpOffice\PhpPresentation\Style\Color;
use PhpOffice\PhpPresentation\Style\Alignment;
use Illuminate\Support\Facades\Log;

class PptxGenerator
{
    protected $presentation;

    public function generate($contentData, $studentInfo, $outputPath)
    {
        try {
            $this->presentation = new PhpPresentation();
            $this->setupPresentationProperties($contentData['title'], $studentInfo);

            // Default slide ni o'chirish
            $this->presentation->removeSlideByIndex(0);

            // Talaba ma'lumotlari (agar birinchi sahifaga)
            if ($studentInfo['info_placement'] === 'first') {
                $this->createStudentInfoSlide($studentInfo, $contentData['title']);
            }

            // Kontent sahifalari
            foreach ($contentData['slides'] as $slideData) {
                $this->createContentSlide($slideData);
            }

            // Talaba ma'lumotlari (agar oxirgi sahifaga)
            if ($studentInfo['info_placement'] === 'last') {
                $this->createStudentInfoSlide($studentInfo, $contentData['title']);
            }

            $this->savePresentation($outputPath);

            return [
                'success' => true,
                'file_path' => $outputPath,
                'file_size' => filesize($outputPath)
            ];

        } catch (\Exception $e) {
            Log::error('PPTX Generation Error: ' . $e->getMessage());
            Log::error('Stack trace: ' . $e->getTraceAsString());
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    protected function setupPresentationProperties($title, $studentInfo)
    {
        $properties = $this->presentation->getDocumentProperties();
        $properties->setCreator($studentInfo['first_name'] ?? 'Student')
            ->setTitle($title)
            ->setSubject($title)
            ->setDescription("Generated by Telegram Presentation Bot")
            ->setCategory("Education");
    }

    /**
     * Talaba ma'lumotlari sahifasi (Background siz - ko'k matn)
     */
    protected function createStudentInfoSlide($studentInfo, $title)
    {
        $slide = $this->presentation->createSlide();

        // Sarlavha (ko'k rangda)
        $shape = $slide->createRichTextShape()
            ->setHeight(100)
            ->setWidth(900)
            ->setOffsetX(50)
            ->setOffsetY(50);

        $shape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $textRun = $shape->createTextRun($title);
        $textRun->getFont()
            ->setBold(true)
            ->setSize(40)
            ->setColor(new Color('FF2C3E50'));

        // Talaba ma'lumotlari
        $infoShape = $slide->createRichTextShape()
            ->setHeight(400)
            ->setWidth(800)
            ->setOffsetX(100)
            ->setOffsetY(200);

        $infoShape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Universitet
        $line1 = $infoShape->createTextRun("🎓 " . $studentInfo['university'] . "\n\n");
        $line1->getFont()->setSize(24)->setColor(new Color('FF3498DB'))->setBold(true);

        // Yo'nalish
        $infoShape->createParagraph();
        $line2 = $infoShape->createTextRun("📚 " . $studentInfo['direction'] . "\n\n");
        $line2->getFont()->setSize(20)->setColor(new Color('FF34495E'));

        // Guruh
        $infoShape->createParagraph();
        $line3 = $infoShape->createTextRun("👥 Guruh: " . $studentInfo['group_name'] . "\n\n");
        $line3->getFont()->setSize(20)->setColor(new Color('FF34495E'));

        // Talaba ismi
        if (!empty($studentInfo['first_name'])) {
            $infoShape->createParagraph();
            $line4 = $infoShape->createTextRun("👤 " . $studentInfo['first_name']);
            $line4->getFont()->setSize(18)->setColor(new Color('FF7F8C8D'));
        }
    }

    /**
     * Kontent sahifasi
     */
    protected function createContentSlide($slideData)
    {
        $slide = $this->presentation->createSlide();

        // Sarlavha
        $titleShape = $slide->createRichTextShape()
            ->setHeight(80)
            ->setWidth(900)
            ->setOffsetX(50)
            ->setOffsetY(30);

        $titleShape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_LEFT);

        $titleRun = $titleShape->createTextRun($slideData['title']);
        $titleRun->getFont()
            ->setBold(true)
            ->setSize(32)
            ->setColor(new Color('FF2C3E50'));

        // Kontent (bullet points)
        $contentShape = $slide->createRichTextShape()
            ->setHeight(500)
            ->setWidth(880)
            ->setOffsetX(70)
            ->setOffsetY(130);

        foreach ($slideData['content'] as $index => $point) {
            if ($index > 0) {
                $contentShape->createParagraph();
            }

            $paragraph = $contentShape->getActiveParagraph();
            $paragraph->getAlignment()
                ->setHorizontal(Alignment::HORIZONTAL_LEFT)
                ->setMarginLeft(25)
                ->setIndent(-25);

            // Bullet
            $paragraph->getBulletStyle()
                ->setBulletType(\PhpOffice\PhpPresentation\Style\Bullet::TYPE_BULLET)
                ->setBulletChar('•');

            $textRun = $contentShape->createTextRun($point);
            $textRun->getFont()
                ->setSize(18)
                ->setColor(new Color('FF34495E'));
        }

        // Sahifa raqami
        $this->addSlideNumber($slide, $slideData['slide_number']);
    }

    protected function addSlideNumber($slide, $number)
    {
        $shape = $slide->createRichTextShape()
            ->setHeight(30)
            ->setWidth(100)
            ->setOffsetX(870)
            ->setOffsetY(690);

        $shape->getActiveParagraph()->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_RIGHT);

        $textRun = $shape->createTextRun((string)$number);
        $textRun->getFont()
            ->setSize(12)
            ->setColor(new Color('FF95A5A6'));
    }

    protected function savePresentation($outputPath)
    {
        $directory = dirname($outputPath);
        if (!file_exists($directory)) {
            mkdir($directory, 0755, true);
        }

        $writer = IOFactory::createWriter($this->presentation, 'PowerPoint2007');
        $writer->save($outputPath);
    }
}
